### PR TITLE
Add CARBUS Analyzer file load.

### PR DESCRIPTION
**Pull request by KostyaSha**
- Generic CSV parses file without failures, so CARBUS must be higher.
- File may be loaded but will have no packets. Adjusted UI message for this case.
- Obviously if we got CANHACKER header, then file is already detected and there is no need to parse.

### CODE REVIEW

**Comment by KostyaSha** [comment]
Is there any plans to get rid off `qApp->processEvents();` ?

**Comment by collin80** [comment]
> Is there any plans to get rid off `qApp->processEvents();` that makes hard to debug application because UI can't render and stuck on monitor?

The whole reason to have qApp->processEvents(); is that it does allow the GUI to actually work. Without it the loading process bar won't even work.

**Comment by KostyaSha** [comment]
> The whole reason to have qApp->processEvents(); is that it does allow the GUI to actually work. Without it the loading process bar won't even work.

From my pure understanding it needs only when hard computation happen in the same thread where UI is rendered. If you move hardwork to separate thread then you can send progress to progressbar slot and UI will process everything in time.

**Comment by collin80** [comment]
You're correct. And, that would be the proper way to go, especially now that basically every processor is multi-core in the extreme. My laptop even has 12 processing threads / 6 cores. So, it would make sense to multi-thread the application further. That would alleviate the need for processEvents() as the GUI thread would almost always be unencumbered by other heavy processing. It just naturally requires that the code be refactored to work that way, especially since only the GUI thread can touch GUI elements. So, it would certainly involve more interprocess information passing. But, such an approach is technically more correct.

**Comment by KostyaSha** [comment]
PS will also make ability to save to their format, already have small cli tool for conversion

**Pull request merged**
