### PR TITLE
Fix icons output dir

### PR DESCRIPTION
**Pull request by D3vil0p3r**
https://github.com/collin80/SavvyCAN/issues/853

### CODE REVIEW

**Comment by collin80** [comment]
I am not sure when the iconfiles.path line was added. Personally I'm nearly always running local builds and don't really look at the icon so I guess I've neglected this. Is it universally always supposed to be just $$PREFIX/share? Why would it have had the icons part for so long? If this is now the correct way to do it then I can merge it in, I'm just not sure why we had it this other way for so long.

**Comment by D3vil0p3r** [comment]
You should detect old commits to investigate on it

**Comment by collin80** [comment]
Hmmm, I added the line myself 5 years ago while trying to get TravisCI to build the code. It's entirely possible it was the proper path back then and isn't now. I'll have to investigate a bit further.

**Comment by D3vil0p3r** [comment]
Hey. Did you have the change to investigate further on the topic?

**Comment by collin80** [comment]
I looked into it and the advice was to use... the exact line I had. Nobody had complained up until now but that doesn't mean it was necessarily right. But, I have no idea why I need this line or why it didn't work properly for you. The mystery deepens...

**Comment by D3vil0p3r** [comment]
No one complains because average users dont know the freedesktop specifications https://specifications.freedesktop.org/icon-theme-spec/latest/

They just use the software. I was aware of this because I'm packaging it for BlackArch.

**Comment by D3vil0p3r** [comment]
Any news on this? I'm using it with that change and I don't see any impact.

**Comment by collin80** [comment]
I've merged it. It seems like you're right and it should have been changed. So, it is now. Thanks.

**Pull request merged**
