### PR TITLE
LAWICEL CAN-FD support, CAN-FD data rate selection

### PR DESCRIPTION
**Pull request by maciek16c**
CAN-FD support for Canable V2. Sending frames not tested, but receiving works

### CODE REVIEW

**Comment by cgalpin** [comment]
@maciek16c thanks a lot for doing this. I can confirm that I can connect to my Canable V2 and see the can traffic in SavvyCAN now!

As for sending, I am not sure exactly what works, but can confirm that using the javascript scripting interface I can send frames and get additional frames back ( I am not sure this is helpful). I have a dbc file for a hyundai ev6 which I believe is compatible with my ioniq5 battery and the data does not show properly in the main data view, but I suspect because the data comes from multiple frames, SavvyCAN can't just assemble it all magically.

@collin80 I am interested in helping improve the CAN-FD support, especially with a GVRET serial connection to the esp32 candue, but it's still not clear to me where the work needed is. if you could nudge me in the right direction I am sure I could help.  

BTW, I am doing this on a raspberry pi 4 using the built in qt5 for debian bullseye and the app is behaving very flakey and crashing often for simple things like resizing windows or trying almost anything in the regular "custom" Frame Sender panel but I assume it's because i haven't tried to build the qt5 from qt.io yet since it takes forever to build.

thank,
charles
Image 12-10-23 at 4 53 PM
Image 12-10-23 at 11 24 AM (1)
Image 12-10-23 at 11 24 AM

**Comment by cgalpin** [comment]
Thanks, i will give this a shot!

Interesting about the UDS. I am new to all of this, but did run [this javascript script](https://github.com/maciek16c/SavvyCAN/blob/4b46537850b13146359f2cf4fb18feecaedc5592/examples/CaptureAllMsgTypes.js) which showed a UDS message with ID 604 and service 3e, but did not know what to make of it.

I will give your script a try later today.

thanks,
charles

**Comment by cgalpin** [comment]
I took a look, and unfortunately adding CAN-FD support for the GVRET connection isn't going to be that simple. I can expose the controls to let the use specify CAN-FD and the data rate, but it looks like the GVRET protocol does not have the CAN-FD support implemented based on what I see in the [ESP32RET project](https://github.com/collin80/ESP32RET/blob/9bd4bf3146ab59064572cee556b456d055dcd504/gvret_comm.h#L24). There are commands defined, but not implemented.

@collin80  can you confirm that the PROTO_SETUP_FD and PROTO_GET_FD commands in the GVRET_PROTOCOL need to be implemented in the ESP32RET project for this to work from SavvyCAN? Right now it looks to me that it can only be enabled over the serial console.

**Comment by collin80** [comment]
Yes, the set up commands need to be implemented on the ESP32RET side yet. It supports sending and receiving CAN-FD messages but not setting up the actual FD connection. For that you do need to use the command line at this point.

**Comment by cgalpin** [comment]
@collin80 I have a bug where the data rate changes I am sending back to the can_due are not getting saved correctly. I am sure it's something related to the data marshaling  and that you will easily identify it. But because of this I don't want to make a pull request.

What's tested/works:

1. The SavvyCAN changes against a plain ESP32RET v618 without changes (backward compatibility)
2. The can_due FD settings are read on connecting, and the bus details set appropriately
3. Lawicel still works (although I don't think changing settings after connecting work, but they didn't work before my changes)

What does not work:

1. the FD data rate is not saved properly. This is what I am observing
```
sent    -> saved
-----------------
1000000 -> 1000000
2000000 -> 951424
4000000 -> 854272
5000000 -> 805696
```
4. Also I can make a change, disconnect the GVRET device, connect via a terminal to the serial port and see changes. However, when I reconnect to the GVRET device, it does not read the changed settings from the device - i am not sure what that is, but not worth digging into until settings are saved properly. A bit confusing :)

Anyway, would you mind taking a look? I am hoping it's something obvious

ESP32RET: [Add-CAN-FD-support-for-GVRET-protocol branch](https://github.com/cgalpin/ESP32RET/tree/Add-CAN-FD-support-for-GVRET-protocol)
SavvyCAN: [Add-CAN-FD-support-for-GVRET-protocol branch](https://github.com/cgalpin/SavvyCAN/tree/ADD-CAN-FD-support-for-GVRET-protocol)

**Comment by collin80** [comment]
> However, as luck would have it, my test case is 500k nominal bus speed, with 2M for FD data, which is not working properly. I assume this is going to need to be fixed in esp32_can, although have not looked and currently have no idea where to start.
> 

Oh... there is certainly an issue at play here. During testing I found that 500k does not work with CAN-FD with the current driver code. If you set the nominal rate to 1M instead then it works at whatever data rate you want. Why doesn't it work with 500k? I never figured out why. Then, I got busy with other things and completely forgot to ever figure it out. So, you're absolutely right, this is a problem in esp32_can in the MCP2517FD driver. To me this error seems very strange since 500k works perfectly fine by itself. 2M data rate also works perfectly fine. But, they don't work together. No doubt it's some sort of bug in the code but I'm not sure where or why.

**Comment by cgalpin** [comment]
Hi Collin, did you get a chance to look at my changes to see if you can spot what I am doing wrong sending/receiving the GVRET messages? I am sure it will be something embarrassingly stupid on my part and easy for you to see.

**Pull request merged**
