### PR TITLE
Wip2

### PR DESCRIPTION
**Pull request by canpadawan**
Hi Collin,

I am trying to integrate socketcan to savvycan. There are a few points I would like to discuss with you before going further.

Best,
CP

To clarify:
_ we have one CanConnection per port? (Can the connection be seen as a device?)
       _ we want to have status reported by the connection like bus connected/not connected?
       _ is there any need for a connection to change its port? (I would rather think if the port name changes, then this is a different connection)
_ we can have several buses per device? (2 in case of gvret?)
       _ can CAN buses report? (connectivity?, speed?)
       _ if speed is different from the one set by the UI, what should we do (stop the device?, update speed? in the UI)

soft architecture:
_ I think that the CANConnectionContainer is not practical. It forces to use thread which might have no added value for some probes -if you connect to socketcand (tcpip daemon) for instance- and might add sync problems.

I would prefer to remove it and let CANConnection creates a thread if it needs one. (I would use one for socketcan, so I can provide an example to others).

I guess the key class here would be CANConnection. 
See comments below:

```c++
class CANConnection : public QObject
{
    Q_OBJECT

public:
    CANConnection(CANFrameModel *, int); // what is base? 
    // do we need the model here, can't we emit a signal catched by the model?
   // can we add portName?
    virtual int getNumBuses();
    int getBusBase(); // same question
    virtual QString getConnTypeName();
    QString getConnPortName();

signals:
    void error(const QString &);
    void frameUpdateRapid(int);
    void frameUpdate(int); // what difference do you want to make?
    void connectionSuccess(CANConnection *); // if this means connection to the port, can we have one signal like connectionStatus() which will report connected/notconnected?
    void connectionFailure(CANConnection *);
    void deviceInfo(int, int); //First param = driver version (or version of whatever you want), second param a status byte // can that change more frequentlyt than connection status?

    //bus number, bus speed, status (bit 0 = enabled, 1 = single wire, 2 = listen only)
    //3 = Use value stored for enabled, 4 = use value passed for single wire, 5 = use value passed for listen only
    //6 = use value passed for speed. This allows bus status to be updated but set that some things aren't really
    //being passed. Just set for things that really are being updated.
    void busStatus(int, int, int);

public slots:
    virtual void run(); // a bit misleading as this is not the QThread::run

    // I would tend to add a couple of functions with descriptions like
    virtual void start()=0; // start connection (start thread if needed)
    virtual void stop()=0; // stop connection (stop thread if needed), caller will then delete the connection
    
    void sendFrameBatch(const QList<CANFrame> *);
    virtual void sendFrame(const CANFrame *);
    virtual void sendFrameBatch(const QList<CANFrame> *);
    virtual void updatePortName(QString); //string version of the port to connect to. This base doesnt know a thing about this value
    virtual void stopFrameCapture(int); //this is now replaced by bus.active right?
    virtual void startFrameCapture(int); //pass bus number. Only if stopped. Defaults to started anyway
    /* this is not safe to use pointers with QueuedConnection */
    virtual void updateBusSettings(CANBus); //reference to the bus that changed.

protected:
    bool quit;
    int numBuses;    
    int busBase; //first bus this class is supposed to handle
    QString portName; //for easy access later on
    QString connType; //what kind of connection this is (socketcan, kvaser, etc)
    bool isConnected; //is the whole device connected? (Is the code connected to the device itself)
    CANFrameModel *model;
};```

### CODE REVIEW

**Comment by collin80** [comment]
I'm not going to claim that most anything I did in WIP2 was very good.

CanConnection is a physical piece of hardware so it can be seen as a device. It could have one or more buses. I suppose most devices would have only one CAN bus but GVRET has two. I don't know of any other hardware that works like that. I think that dual bus devices from Kvaser and the like would create two devices in the /dev tree so they'd be independent. But, GVRET is connected over a single serial connection for both buses so there really does have to be a way for it to register two buses with one single hardware connection to the PC. 

I think I had CanConnection reporting the status of buses just to abstract the implementation of buses away from the the calling code. 

I don't know that there is any reason that a CanConnection should change ports. As you said, if the port changes it'd probably be easier to just delete the old object and recreate another one with the proper parameters.

As it has been, the buses report things like speed and connection when they start up and then issue a message if the connection died or something.

What I had done previously with speed was to set the hardware to the requested speed from the GUI if the GUI had a requested speed. There should have been a <Default> option that would instead update the GUI to be the same speed as the hardware was last set to.

CanConnectionContainer is kind of a lame kludge. I don't remember exactly why I did that. I think I wondered if a class could create a thread and then move itself to that thread. If it can (which I never checked) then there's no reason for CanConnectionContainer to exist. Even if a class can't move itself there is probably a better solution than this one.

I have a direct reference to the model just for speed reasons. The inter-thread message queue is not that fast and if you have 4000 frames per second flying and the underlying class that is dealing with the hardware tries to send 4000 messages per second over a queued signal/slot it will not work. I've found that it rapidly brings the PC to its knees. So, instead I did the rotten thing and gave everyone the ability to grab a reference to the model and issue direct calls to add frames. Yes, this could lead to some nasty problems which I tried to deal with. The better solution would probably be to queue up messages internally to the CanConnection based class and then send periodic messages over the queued signal/slot interface to the model. That brings the synchronization into Qt a bit more. But, then each CanConnection based class would have to be careful to pass the queued up frames in a safe way. 

You also had a question about what is the "base" variable. I was trying to track which buses were handled by which classes. I don't remember any reason the actual classes that talk with connected hardware would need to know their own base number. Instead it seems like they should just be told to send messages and the managing classes surrounding them should worry about who handles which buses.

Anyway, feel free to correct any stupidity that you find. It sounds like you know what you're doing. What I'm seeing so far looks pretty good. Thanks for working on this stuff.

**Comment by canpadawan** [comment]
Hi Collin,

I have reworked the device abstraction.

good news first:
_ devices are fully abstracted (API described in canconnection.h - see especially pure virtual functions)
_ device can work with our without working thread
_ it works smoothly with 10K messages/sec

and the bad:
_ As I don't have a gvret, I have just made a copy/paste of your code and for sure it's not going to work at first try.
_ I have not implemented sendframes yet
_ a few events are also not implemented

There are several changes here. So I don't think I should go any further before you review it and discuss it.

Good reading & test ;-)

**Comment by collin80** [comment]
I took a look at the commit request and the changes look pretty good on the surface. The only thing I'd really change for sure is that the frames from CAN sources should batch out to the model faster than 250ms. Really, some things might be critical enough to require 5ms. I don't think that 200 signals per second would really be too bad. It's when you get to 4000 per second that things get wonky. I'll merge the pull request in locally when I get a chance and try it out. That might not fully happen until some time this weekend.

**Comment by canpadawan** [comment]
there is no rush, I appreciate you have other things to do than reviewing others code during your free time.

Regarding the can frame exchange. I have taken special care to make sure that nothing can prevent the device to collect frames even if the UI is lagging.
Data are collected by the connection as fast as possible but the UI is not refreshed every time a new frame is available.

I have tried to make sure there would be no priority inversion between the UI thread (low priority) and connection thread (high priority).
To do that I have implemented a lock free queue (no mutex - see utils/lfqueue.h)
* connection writes to it as fast as it can.
* UI pops values from it every 500ms
 * this should be configurable but is not yet
 * it really consumes CPU to do a refresh, but you might have good reasons to do it more frequently.
 * the size is fixed to guarantee that if the UI lags or stalls we don't waste the full RAM.
 * here the connection might emit a signal to advise it's dropping frames.

an example: 
* queue at connections/socketcan.cpp:166
* all connections are dequeued in connectionwindow.cpp:107

So now the only priority inversion we can have is when the UI thread calls connection thread which leads to one of the following function:
```c++

virtual bool piGetBusSettings(int pBusIdx, CANBus& pBus) = 0; /* on this one we can do something if needed */

/* for those 2 I have ideas we could discuss later */
virtual void piSendFrame(const CANFrame&) = 0; 
virtual void piSendFrameBatch(const QList<CANFrame>&) = 0; 
```

Best,

**Comment by collin80** [comment]
Good news, it works both in SocketCAN and GVRET. The only thing I noticed is that the frames per second don't seem to update. But, both device types seem to properly receive traffic.  So, this is very good progress. The other things can be figured out piece by piece. 

I had found that 1/4 second GUI updates only loaded up my machine to about 8-10% CPU load. 

The way it used to work is this:
1. First a device handler (such as serialworker) would capture frames however they do that and then immediately store them in the can frames model. They'd keep track of how many frames they've gotten since last updating anyone
2. At the end of capturing a batch of frames they'd emit a signal that specifies how many frames were captured. These frames, remember, are in the CAN model already
3. Anything that cares about very fast frame updates would then get the signal and decide what to do.
4. The main screen also captured fast frames but just added them to the # of frames that arrived since the last GUI update
5. The main screen had a 250ms GUI updating timer which would trigger, see how many frames were new, refresh the GUI, and emit a signal for slower updates. Anything that cared about frames but didn't need super fast updates would receive this signal and do work.

This scheme was not particularly thread safe because everything accessed the same model and directly injected or received frames from the same place. So, I had mutexes around practically everything. This worked up to thousands of frames per second but it was kind of brittle. I had to be really careful with how everything meshed together. I like the idea of a lock free queue that each device fills up. I still think that queue should be emptied to the master frames list more often. I don't see a reason why it could not be done every 5 or 10ms. Except, I believe that the normal timer granularity on Windows is something like 10ms. However, QT seems to properly set Windows to use higher resolution timers as I've been able to get pretty close to 1ms precision on timers. Thus, a 5ms timer should be perfectly possible on all platforms. A similar scheme to how it was before could still be used: batch out to the master QVector of frames rapidly and send fast updates to anything that needs them but still keep the GUI at a much slower pace. This did work pretty well for me. With your work it could perhaps be even more stable.

So, really my biggest issue is the ability to still have various pieces of code be able to get signals at high speed when traffic is flying. This was useful for ECU simulators (via the ability to write scripts in javascript that respond to can frames), firmware updating, and the custom sender window (very much like the scripting window - used to respond to frames with other frames). Those sort of things need frames right now. Pretty much everything else can update 1-2 times per second for all I care. I picked 4 times per second as a reasonable compromise but that's not set in stone.

I merged what you have so far. This is the first time in a while that the WIP2 branch even sort of worked. Great work so far.

**Pull request merged**
